data:
  augmentation:
    auto_augment: rand-m9-mstd0.5-inc1
    color_jitter: 0.4
    re_prob: 0.25
  dataset_name: cotton80
  num_workers: 4
  root: ./data
experiment:
  notes: Default ResNet-50 (ReLU + BatchNorm)
  project_name: IHA-BMCN-UFGVC
  tags:
  - B1
  - cotton80
  variant: B1
model:
  bmcn:
    affine: true
    eps: 1.0e-05
    momentum: 0.1
  iha:
    eps: 1.0e-05
    kappa_init: 0.1
    per_channel: false
  name: resnet50
  pretrained: true
training:
  batch_size: 16
  epochs: 50
  grad_clip: 5.0
  learning_rate: 0.0005
  output_dir: ./outputs
  seed: 42
  warmup_ratio: 0.05
  weight_decay: 0.05
